export const terms = {

    title: 'The Software WEBSITE TERMS OF USE IMPORTANT - PLEASE READ',
    toptext: [
        'Thank you for visiting the website (the “Website”) on which you found the link to these Terms Of Use (the “Website”). The Website is an Internet property of TheSoftware. (referred to collectively as “TheSoftware,” “we” and “us”). You agree to be bound by these TheSoftware Website Terms of Use (“Terms of Use”), in their entirety, when you: (a) access the Website; (b) register for a newsletter or subscribe to a mailing list or request information by and through the Website (“Subscription Services”); (c) register to participate in promotions, contests and/or sweepstakes offered by TheSoftware from time to time (each, a “Contest”); (d) join, or attempt to join, an affiliate program or other membership organization featured on the Website (“Membership Services”); and/or (e) order a product and/or service through the Website (“Vendor Services, and together with the Subscription Services and Membership Services, the “Services”). TheSoftware Privacy Policy (“Privacy Policy”), the Official Contest Rules applicable to each Contest, TheSoftware Purchase Agreement(s) (“Purchase Agreement”), TheSoftware Membership Agreement(s) (“Membership Agreement”), as well as any other operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time, are expressly incorporated herein by reference (collectively, the “Agreement”). Please review the complete terms of the Agreement carefully. If you do not agree to the Agreement in its entirety, you are not authorized to use the Services and/or Website in any manner or form.',
        'TheSoftware SPECIFICALLY DENIES ACCESS TO THE WEBSITE AND/OR SERVICES BY ANY INDIVIDUAL THAT IS COVERED BY THE CHILDREN’S ONLINE PRIVACY PROTECTION ACT OF 1998, AS AMENDED (“COPPA”). TheSoftware RESERVES THE RIGHT TO DENY ACCESS TO THE SERVICES AND/OR WEBSITE TO ANY INDIVIDUAL, IN ITS SOLE AND EXCLUSIVE DISCRETION.'
    ],
    sections: [
        {
            title: 'SCOPE AND MODIFICATION OF THE AGREEMENT',
            text: ['You agree to the terms and conditions outlined in the Agreement with respect to your use of the Website. The Agreement constitutes the entire and only agreement between you and TheSoftware with respect to your use of the Website and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to the Website. We may amend the Agreement from time to time in our sole discretion, without specific notice to you. The latest Agreement will be posted on the Website, and you should review the Agreement prior to using the Website. By your continued use of the Website and/or Services, you hereby agree to comply with all of the terms and conditions contained within the Agreement effective at that time. Therefore, you should regularly check this page for updates and/or changes.']
        },
        {
            title: 'REQUIREMENTS',
            text: ['The Website and Services are available only to individuals who can enter into legally binding contracts under applicable law. The Website and Services are not intended for use by individuals under the age of eighteen (18). If you are under the age of eighteen (18), you do not have permission to use and/or access the Website and/or Services.']
        },
        {
            title: 'DESCRIPTION OF THE SERVICES',
            text: [
                'Subscription Services',
                'Subject to the terms and conditions of the Agreement, by registering on the Website and receiving approval from TheSoftware, you can obtain, or attempt to obtain, for a fee or for no fee, the Subscription Services. The Subscription Services will provide you with e-mail content, text and other materials (“Subscription Content”) relevant to online marketing provided by TheSoftware and its third party partners (“Third Party Providers”). If you would like to discontinue receipt of the Subscription Content, simply email us at support@fxrevenge.net. The Subscription Content contains comments, opinions and/or other materials that are provided by TheSoftware and Third Party Providers, and should not necessarily be relied upon. Please use caution, common sense and safety when using the Subscription Content and/or Subscription Services. You agree that TheSoftware shall have no obligations and incur no liabilities to you in connection with any such Subscription Content. TheSoftware does not represent or warrant that the Subscription Content made available in connection with the Subscription Services is accurate, complete or appropriate. You understand and agree that TheSoftware is not responsible or liable in any manner whatsoever for your inability to use the Subscription Services and/or Subscription Content. You understand and agree that TheSoftware shall not be liable to you, any end-users or any third party, for any claim in connection with any of the Subscription Services.',
                'Membership Services',
                'Subject to the terms and conditions of the Agreement and the Membership Agreement, by registering on the Website, agreeing to the Membership Agreement and receiving approval from TheSoftware, you can obtain, or attempt to obtain, for a fee or for no fee, a Membership in one of the various Membership programs that MTS Advertise OU offers. For a copy of the Membership Agreement, please visit the website for the specific Membership. TheSoftware Membership programs will enable you to access content, text and other materials (“Member Content” and together with the Subscription Content, the “Content”) provided by TheSoftware and certain Third Party Providers, designed to assist Members in their online marketing ventures. The Member Content contains comments, opinions and other materials that are provided by TheSoftware Third Party Providers, and should not necessarily be relied upon. Please use caution, common sense and safety when using the Member Content and/or Membership Services. You agree that TheSoftware shall have no obligations and incur no liabilities to you in connection with any such Member Content. TheSoftware does not represent or warrant that the Member Content made available in connection with the Membership Services is accurate, complete or appropriate. You understand and agree that TheSoftware is not responsible or liable in any manner whatsoever for your inability to use the Membership Services and/or Member Content. You understand and agree that TheSoftware shall not be liable to you, any end-users or any third party, for any claim in connection with any of the Membership Services.',
                'Vendor Services',
                'By completing the applicable purchase order forms, you can obtain, or attempt to obtain, certain products and/or services from the Website. The products and/or services featured on the Website may contain descriptions that are provided directly by the Third Party Provider manufacturers or distributors of such items. TheSoftware does not represent or warrant that the descriptions of such items are accurate or complete. You understand and agree that TheSoftware is not responsible or liable in any manner whatsoever for your inability to obtain products and/or services from the Website or for any dispute with the product’s seller, distributor and end-user consumers. You understand and agree that TheSoftware shall not be liable to you or any third party for any claim in connection with any of the products and/or services offered on the Website.',
                'General',
                'The information that you must supply in connection with registering for the Services may include, without limitation, some or all of the following: (a) your full name; (b) company name; (c) e-mail address; (d) mailing address (and billing address if different); (e) home telephone number; (f) work telephone number; (g) telecopier number; (h) credit card information; and/or (i) any other information requested on the applicable registration form (“Service Registration Data”). You agree to provide true, accurate, current and complete Service Registration Data. TheSoftware has the right to reject any Service Registration Data where it is determined, in the sole and exclusive discretion of TheSoftware, that: (i) you are in breach of any portion of the Agreement; and/or (ii) the Service Registration Data that you provided is incomplete, fraudulent, a duplicate or otherwise unacceptable. TheSoftware may change the Registration Data criteria at any time, in its sole discretion.',
                'Unless explicitly stated otherwise, any future offer(s) made available to you on the Website that augment(s) or otherwise enhance(s) the current features of the Website shall be subject to the Agreement. You understand and agree that TheSoftware is not responsible or liable in any manner whatsoever for your inability to use and/or qualify for the Services. You understand and agree that TheSoftware shall not be liable to you or any third party for any modification, suspension or discontinuation of any Services or other product, service or promotion offered by TheSoftware and/or any of its Third Party Providers. If MTS Advertise OU terminates the Agreement and/or any Services for any reason, MTS Advertise OU shall have no liability or responsibility to you. You understand and agree that refusal to use the Website is your sole right and remedy with respect to any dispute that you may have with TheSoftware.',
            ]
        },
        {
            title: 'CONTESTS',
            text: ['From time-to-time, TheSoftware offers promotional prizes and other awards via Contests. By providing true and accurate information in connection with the applicable Contest registration form, and agreeing to the Official Contest Rules applicable to each Contest, you can enter for a chance to win the promotional prizes offered through each Contest. To enter into the Contests featured on the Website, you must first fully complete the applicable entry form. You agree to provide true, accurate, current and complete Contest Registration Data. TheSoftware has the right to reject any Contest Registration Data where it is determined, in the sole and exclusive discretion of TheSoftware, that: (i) you are in breach of any portion of the Agreement; and/or (ii) the Contest Registration Data that you provided is incomplete, fraudulent, a duplicate or otherwise unacceptable. TheSoftware may change the Registration Data criteria at any time, in its sole discretion.'],
        },
        {
            title: 'LICENSE GRANT',
            text: ['As a user of the Website, you are granted a non-exclusive, non-transferable, revocable and limited license to access and use the Website, Content and associated material in accordance with the Agreement. TheSoftware may terminate this license at any time for any reason. You may use the Website and Content on one computer for your own personal, non-commercial use. No part of the Website, Content, Contests and/or Services may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical. You may not use, copy, emulate, clone, rent, lease, sell, modify, decompile, disassemble, reverse engineer or transfer the Website, Content, Contests and/or Services or any portion thereof. TheSoftware reserves any rights not explicitly granted in the Agreement. You may not use any device, software or routine to interfere or attempt to interfere with the proper working of the Website. You may not take any action that imposes an unreasonable or disproportionately large load on TheSoftware’s infrastructure. Your right to use the Website, Content, Contests and/or Services is not transferable.'],
        },
        {
            title: 'PROPRIETARY RIGHTS',
            text: ['The content, organization, graphics, design, compilation, magnetic translation, digital conversion, software, services and other matters related to the Website, Content, Contests and Services are protected under applicable copyrights, trademarks and other proprietary (including, but not limited to, intellectual property) rights. The copying, redistribution, publication or sale by you of any part of the Website, Content, Contests and/or Services is strictly prohibited. Systematic retrieval of material from the Website, Content, Contests and/or Services by automated means or any other form of scraping or data extraction in order to create or compile, directly or indirectly, a collection, compilation, database or directory without written permission from TheSoftware is prohibited. You do not acquire ownership rights to any content, document, software, services or other materials viewed at or through the Website, Content, Contests and/or Services. The posting of information or material on the Website, or by and through the Services, by TheSoftware does not constitute a waiver of any right in or to such information and/or materials. The TheSoftware name and logo, and all associated graphics, icons and service names, are trademarks of TheSoftware. All other trademarks appearing on the Website or by and through the Services are the property of their respective owners. The use of any trademark without the applicable owner’s express written consent is strictly prohibited.'],
        },
        {
            title: 'HYPERLINKING TO THE WEBSITE, CO-BRANDING, "FRAMING" AND/OR REFERENCING THE WEBSITE PROHIBITED',
            text: ['Unless expressly authorized by TheSoftware, no one may hyperlink the Website, or portions thereof (including, but not limited to, logotypes, trademarks, branding or copyrighted material), to their website or web venue for any reason. Further, ”framing” the Website and/or referencing the Uniform Resource Locator (”URL”) of the Website in any commercial or non-commercial media without the prior, express, written permission of TheSoftware is strictly prohibited. You specifically agree to cooperate with the Website to remove or cease, as applicable, any such content or activity. You hereby acknowledge that you shall be liable for any and all damages associated therewith.'],
        },
        {
            title: 'EDITING, DELETING AND MODIFICATION',
            text: ['We reserve the right in our sole discretion to edit and/or delete any documents, information or other content appearing on the Website.'],
        },
        {
            title: 'DISCLAIMER',
            text: ['THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE ARE PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS AND ALL WARRANTIES, EXPRESS AND IMPLIED, ARE DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW (INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY AND/OR FITNESS FOR A PARTICULAR PURPOSE). IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, TheSoftware MAKES NO WARRANTY THAT: (A) THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE WILL MEET YOUR REQUIREMENTS; (B) THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (C) YOU WILL QUALIFY FOR THE CONTESTS AND/OR SERVICES; OR (D) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE WILL BE ACCURATE OR RELIABLE. THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. WE WILL NOT BE LIABLE FOR THE AVAILABILITY OF THE UNDERLYING INTERNET CONNECTION ASSOCIATED WITH THE WEBSITE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM TheSoftware, ANY OF ITS THIRD PARTY PROVIDERS OR OTHERWISE THROUGH OR FROM THE WEBSITE, SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT.'],
        },
        {
            title: 'DISCLAIMER FOR HARM CAUSED BY DOWNLOADS',
            text: ['Visitors download information from the Website at their own risk. TheSoftware makes no warranty that such downloads are free of corrupting computer codes including, but not limited to, viruses and worms.'],
        },
        {
            title: 'LIMITATION OF LIABILITY',
            text: ['YOU EXPRESSLY UNDERSTAND AND AGREE THAT TheSoftware SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL AND/OR EXEMPLARY DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF TheSoftware HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), TO THE FULLEST EXTENT PERMISSIBLE BY LAW FOR: (A) THE USE OR THE INABILITY TO USE THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION AND/OR SERVICES PURCHASED OR OBTAINED FROM, OR TRANSACTIONS ENTERED INTO THROUGH, THE WEBSITE; (C) THE FAILURE TO QUALIFY FOR THE CONTESTS, SERVICES OR THIRD PARTY PRODUCTS FROM ANY OF OUR THIRD PARTY PROVIDERS, OR ANY SUBSEQUENT DENIAL OF THIRD PARTY PRODUCTS FROM SAME; (D) THE UNAUTHORIZED ACCESS TO, OR ALTERATION OF, YOUR REGISTRATION DATA; AND (E) ANY OTHER MATTER RELATING TO THE INABILITY TO USE THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION, IN THE AGGREGATE INCLUDING, BUT NOT LIMITED TO, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATIONS AND ANY AND ALL OTHER TORTS. YOU HEREBY RELEASE TheSoftware AND ALL OF TheSoftware’S THIRD PARTY PROVIDERS FROM ANY AND ALL OBLIGATIONS, LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATION STATED HEREIN. IF APPLICABLE LAW DOES NOT PERMIT SUCH LIMITATION, THE MAXIMUM LIABILITY OF TheSoftware TO YOU UNDER ANY AND ALL CIRCUMSTANCES WILL BE FIVE HUNDRED DOLLARS ($500.00). THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND TheSoftware. THE INABILITY TO USE THE WEBSITE, SERVICES, CONTESTS, CONTENT, ANY THIRD PARTY PRODUCTS THAT YOU MAY RECEIVE FROM ONE OF OUR THIRD PARTY PROVIDERS, AND/OR ANY OTHER PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE WEBSITE WOULD NOT BE PROVIDED TO YOU WITHOUT SUCH LIMITATIONS.'],
        },
        {
            title: 'INDEMNIFICATION',
            text: ['You agree to indemnify and hold TheSoftware, each of their parents, subsidiaries and affiliates, and each of their respective members, officers, directors, employees, agents, co-branders and/or other partners, harmless from and against any and all claims, expenses (including reasonable attorneys’ fees), damages, suits, costs, demands and/or judgments whatsoever, made by any third party due to or arising out of: (a) your use of the Website, Services, Content and/or entry into any Contest; (b) your breach of the Agreement; and/or (c) your violation of any rights of another individual and/or entity. The provisions of this paragraph are for the benefit of TheSoftware, each of their parents, subsidiaries and/or affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.'],
        },
        {
            title: 'DISCLAIMER FOR HARM CAUSED BY DOWNLOADS',
            text: ['Visitors download information from the Website at their own risk. TheSoftware makes no warranty that such downloads are free of corrupting computer codes including, but not limited to, viruses and worms.'],
        },
        {
            title: 'THIRD PARTY WEBSITES',
            text: ['The Website may provide links to and/or refer you to other Internet websites and/or resources including, but not limited to, those owned and operated by Third Party Providers. Because TheSoftware has no control over such third party websites and/or resources, you hereby acknowledge and agree that TheSoftware is not responsible for the availability of such third party websites and/or resources. Furthermore, TheSoftware does not endorse, and is not responsible or liable for, any terms and conditions, privacy policies, content, advertising, services, products and/or other materials at or available from such third party websites or resources, or for any damages and/or losses arising therefrom.'],
        },
        {
            title: 'PRIVACY POLICY/VISITOR INFORMATION',
            text: ['Use of the Website, and all comments, feedback, information, Registration Data and/or materials that you submit through or in association with the Website, is subject to our Privacy Policy. We reserve the right to use all information regarding your use of the Website, and any and all other personally identifiable information provided by you, in accordance with the terms of our Privacy Policy. To view our Privacy Policy, please Click Here.'],
        },
        {
            title: 'LEGAL WARNING',
            text: ['Any attempt by any individual, whether or not a TheSoftware customer, to damage, destroy, tamper with, vandalize and/or otherwise interfere with the operation of the Website, is a violation of criminal and civil law and TheSoftware will diligently pursue any and all remedies in this regard against any offending individual or entity to the fullest extent permissible by law and in equity.'],
        },
        {
            title: 'CHOICE OF LAW/VENUE',
            text: ['Any disputes arising out of or related to the Agreement shall be governed by and construed in accordance with the laws of Estonia (without regard to conflict of law principles). Any award rendered shall be final and conclusive to the parties and a judgment thereon may be entered in any court of competent jurisdiction. Nothing herein shall be construed to preclude any party from seeking injunctive relief in order to protect its rights pending an outcome in arbitration. To the extent permitted by law, you agree that you will not bring, join or participate in any class action lawsuit as to any claim, dispute or controversy that you may have against TheSoftware. and each of their legal representatives, affiliates, subsidiaries, parents, agencies and their respective members, officers, directors, employees and agents. You agree to the entry of injunctive relief to stop such a lawsuit or to remove you as a participant in the suit. You agree to pay the attorney’s fees and court costs that TheSoftwareurs in seeking such relief. The Agreement does not constitute a waiver of any of your rights and remedies to pursue a claim individually and not as a class action in binding arbitration as provided above. This provision preventing you from bringing, joining or participating in class action lawsuits is an independent agreement. Should any part of the Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect.'],
        },
    ]  
}

export const privacy = {

    title: 'The Software Privacy Policy',
    toptext: [
        'By clicking on "Continue", you are giving us permission to send you emails about our offers. If you chose not to receive any more emails, you can always opt out at any time at the bottom of each email.',
        'The Software respects the privacy of every individual who visits our websites. This privacy statement provides notice of the standards and terms under which The Software protects the privacy of information supplied by visitors to sites on the World Wide Web that are owned and operated by The Software, including The Software and The Software. This privacy statement provides notice of our information collection practices and of the ways in which your information may be used. This policy may change from time to time, so please check back periodically to review this information.'
    ],
    sections: [
        {
            title: 'A. Personally-Identifiable Information:',
            text: ['The Software typically receives specific data about its website visitors only when such information is provided voluntarily, such as when our visitors request information, purchase or enroll for services, open a customer support inquiry ticket, provide resume information for employment opportunities, or send us e-mail. Of course, some of these activities require that you give us information, such as when you make a purchase, use a credit card to pay for services, submit your resume, or request certain types of information. When you provide personally- identifiable information to The Software through one of our websites, it will be used to fulfill your specific request. In most cases, you will be given the opportunity to select whether you do, or do not, want The Software to use this information for additional purposes. You may also request that The Software not use your information by sending an e-mail to: support@fxrevenge.net, however, The Software reserves the right, in its discretion, to send you bulletins and other important information about your The Software services. Absent any instructions from you, The Software may use information you provide to inform you about additional services and products offered by the The Software family of companies, The Software authorized agents, and other goods and services providers with whom The Software has relationships and whose offerings might be of interest to you. The Software will not, however, sell or trade your personally-identifiable information unless we are authorized or legally required to do so, or in the case of imminent physical harm to the visitor or others. On those The Software sites where you may provide The Software with credit card or other ordering information via the web, The Software protects and secures this information by employing commercially customary web- based security and encryption protocols, examples of which include Secure Socket Layer (SSL) and Secure Electronic Transaction (SET). On those sites where you voluntarily offer any feedback, data, answers, questions, comments, suggestions, ideas or the like, The Software will treat that portion of the information as non-confidential and nonproprietary and, except as otherwise expressed in this privacy statement, The Software assumes no obligation to protect such information from disclosure.',
                    'Examples in these materials are not to be taken as a promise or guarantee of earnings. Earning potential is entirely dependent on the person using our product, ideas, techniques and the effort put forth. We do not purport this as a "get rich scheme", and nor should you view it as such.']
        },
        {
            title: 'B. Non Personally-Identifiable (Generic) Information:',
            text: ['In general, The Software gathers some generic information automatically. Generic information does not reveal the identity of the visitor. It usually includes information about the Internet address assigned to your computer, the number and frequency of visitors, and the The Software sites visited. The Software gathers this information for the limited purpose of determining customer service and website needs. We accomplish this by using certain technologies, including "cookies" (a technology that can be used to provide the visitor with tailored information about The Software services). The Software does not combine information collected in this way with any personally-identifiable information. You can set your browser to notify you when you receive a cookie and you can refuse it.']
        },
        {
            title: 'C. Your The Software hosted website, server, bulletin boards, forum, Third-Party Sites:',
            text: [
                'Information that you disclose in a public space, including on any bulletin board, chat room, or website The Software may host for you as part of your The Software services, is available to anyone else who visits that space. The Software cannot safeguard any information you disclose in these locations. Additionally, The Software websites contain links to sites that belong to third parties unrelated to The Software. The Software cannot protect any information you may disclose in these sites and recommends that you review the privacy policy statements of those sites you visit.',
            ]
        },
        {
            title: 'D. Exceptions and Limitations:',
            text: [
                'Notwithstanding the foregoing and in compliance with applicable laws, The Software (i) cooperates fully with state, local, and federal officials in any investigation relating to any content (including personal or private electronic communications transmitted to The Software) or purported unlawful activities of any user of the Service, and (ii) takes reasonable measures to protect its proprietary rights. For the limited purposes of accomplishing such cooperation and measures and in compliance with applicable laws, The Software may be required to disclose personally identifiable information. In addition, The Software may elect to monitor the areas of communication of any kind (i) to satisfy any law, regulation, or government request; (ii) if such disclosure is necessary or appropriate to operate The Software; or (iii) to protect the rights or property of The Software or others. In connection with the potential sale or transfer of any of its interest in The Software and The Software and other sites owned by the company, The Software reserves the right to sell or transfer your information (including , but not limited to name, address information, and other information you provided to The Software) to a third party that (i) concentrates its business in communication products or services; (ii) agrees to be The Software\'s successor in interest with regard to the maintenance and protection of information collected and maintained by The Software; and (iii) agrees to the obligations of this policy statement.',
            ]
        },
    ]  
}

export const gov = {

    title: 'The Software U.S. Government Required Disclaimer',
    toptext: [
        'U.S. Government Required Disclaimer - Trading foreign exchange on margin carries a high level of risk, and may not be suitable for all investors. The high degree of leverage can work against you as well as for you. Before deciding to invest in foreign exchange you should carefully consider your investment objectives, level of experience, and risk appetite. The possibility exists that you could sustain a loss of some or all of your initial investment and therefore you should not invest money that you cannot afford to lose. You should be aware of all the risks associated with foreign exchange trading, and seek advice from an independent financial advisor if you have any doubts.',
        'The purchase, sale or advice regarding a currency can only be performed by a licensed Broker/Dealer. Neither us, nor our affiliates or associates involved in the production and maintenance of these products or this site, is a registered Broker/Dealer or Investment Advisor in any State or Federally-sanctioned jurisdiction. All purchasers of products referenced at this site are encouraged to consult with a licensed representative of their choice regarding any particular trade or trading strategy. No representation is being made that any account will or is likely to achieve profits or losses similar to those discussed on this website. The past performance of any trading system or methodology is not necessarily indicative of future results.',
        'Clearly understand this: Information contained in this product are not an invitation to trade any specific investments. Trading requires risking money in pursuit of future gain. That is your decision. Do not risk any money you cannot afford to lose. This document does not take into account your own individual financial and personal circumstances. It is intended for educational purposes only and NOT as individual investment advice. Do not act on this without advice from your investment professional, who will verify what is suitable for your particular needs & circumstances. Failure to seek detailed professional personally tailored advice prior to acting could lead to you acting contrary to your own best interests & could lead to losses of capital.',
        '*CFTC RULE 4.41 - HYPOTHETICAL OR SIMULATED PERFORMANCE RESULTS HAVE CERTAIN LIMITATIONS. UNLIKE AN ACTUAL PERFORMANCE RECORD, SIMULATED RESULTS DO NOT REPRESENT ACTUAL TRADING. ALSO, SINCE THE TRADES HAVE NOT BEEN EXECUTED, THE RESULTS MAY HAVE UNDER-OR-OVER COMPENSATED FOR THE IMPACT, IF ANY, OF CERTAIN MARKET FACTORS, SUCH AS LACK OF LIQUIDITY. SIMULATED TRADING PROGRAMS IN GENERAL ARE ALSO SUBJECT TO THE FACT THAT THEY ARE DESIGNED WITH THE BENEFIT OF HINDSIGHT. NO REPRESENTATION IS BEING MADE THAT ANY ACCOUNT WILL OR IS LIKELY TO ACHIEVE PROFIT OR LOSSES SIMILAR TO THOSE SHOWN.',
        'THIS SITE AND THE PRODUCTS AND SERVICES OFFERED ON THIS SITE ARE NOT ASSOCIATED, AFFILIATED, ENDORSED, OR SPONSORED BY GOOGLE, CLICKBANK, CLICKSURE, AMAZON, YOUTUBE, YAHOO OR BING NOR HAVE THEY BEEN REVIEWED TESTED OR CERTIFIED BY GOOGLE, CLICKBANK, YAHOO, AMAZON, YOUTUBE OR BING. ALL PERSONS PORTRAYED ARE REAL AND VERIFIED. IN SOME CASES ACTORS HAVE BEEN USED TO REPRESENT THESE PERSONS. THIS IS A NEW SYSTEM, SO THERE ARE NO TYPICAL RESULTS. THE COMPANY DOES NOT GUARANTEE INCOME OR SUCCESS, AND EXAMPLES OF THE PRODUCT OWNER`S AND OTHER PERSON`S RESULTS DO NOT REPRESENT AN INDICATION OF FUTURE SUCCESS OR EARNINGS.',
    ],
    sections: []
    
}

export const disc = {

    title: 'The Software Earnings Disclaimer',
    toptext: [
        'EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND IT’S POTENTIAL. EVEN THOUGH THIS INDUSTRY IS ONE OF THE FEW WHERE ONE CAN WRITE THEIR OWN CHECK IN TERMS OF EARNINGS, THERE IS NO GUARANTEE THAT YOU WILL EARN ANY MONEY USING THE TECHNIQUES AND IDEAS IN THESE MATERIALS. EXAMPLES IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF EARNINGS. EARNING POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING OUR PRODUCT, IDEAS AND TECHNIQUES. WE DO NOT PURPORT THIS AS A "GET RICH SCHEME."ANY CLAIMS MADE OF ACTUAL EARNINGS OR EXAMPLES OF ACTUAL RESULTS CAN BE VERIFIED UPON REQUEST. YOUR LEVEL OF SUCCESS IN ATTAINING THE RESULTS CLAIMED IN OUR MATERIALS DEPENDS ON THE TIME YOU DEVOTE TO THE PROGRAM, IDEAS AND TECHNIQUES MENTIONED, YOUR FINANCES, KNOWLEDGE AND VARIOUS SKILLS. SINCE THESE FACTORS DIFFER ACCORDING TO INDIVIDUALS, WE CANNOT GUARANTEE YOUR SUCCESS OR INCOME LEVEL. NOR ARE WE RESPONSIBLE FOR ANY OF YOUR ACTIONS.',
        'MATERIALS IN OUR PRODUCT AND OUR WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS "ANTICIPATE," "ESTIMATE," "EXPECT," "PROJECT," "INTEND," "PLAN," "BELIEVE," AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.',
        'ANY AND ALL FORWARD LOOKING STATEMENTS HERE OR ON ANY OF OUR SALES MATERIAL ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT IN DETERMINING YOUR ACTUAL RESULTS AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSES, IN FACT NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.',
        'The author and publisher disclaim any warranties (express or implied), merchantability, or fitness for any particular purpose. The author and publisher shall in no event be held liable to any party for any direct, indirect, punitive, special, incidental or other consequential damages arising directly or indirectly from any use of this material, which is provided "as is", and without warranties.',
        'As always, the advice of a competent legal, tax, accounting or other professional should be sought. The author and publisher do not warrant the performance, effectiveness or applicability of any sites listed or linked to in this TheSoftware.',
        'All links are for information purposes only and are not warranted for content, accuracy or any other implied or explicit purpose.',
    ],
    sections: [
        {
            title: 'Privacy',
            text: [
                'We maintain this page to demonstrate our firm commitment to the rights and privacy of our users. This page explains how our site collects information from our members.',
                'Free Newsletter and mailing list: we respect the privacy of our users, and as such we will never share our database of email addresses and names with any third party.',
                'Upon confirmation that you would like to join our newsletter, we will from time to time send you free information relating to the products we market, general advice related to online marketing, and promotional material for other products. Your email will never be passed onto any third party. We will also never spam you. You may unsubscribe from the mailing list at any time.',
                'Personal Information we collect and how it is used: Service provider: when you purchase TheSoftware, the payment is processed by Clicksure.com, who will collect your name, address, and credit card information so as to verify your order. They may not use the information for any other purpose. Upon ordering, we also collect your name and e-mail address. We use this information to follow-up on you as per the above newsletter section.',
            ]
        },
        {
            title: 'Further Reminder - Earnings Disclaimer:',
            text: [
                'Every effort has been made to accurately represent this product and it`s potential. Even though this industry is one of the few where one can write their own check in terms of earnings, there is no guarantee that you will earn any money using the techniques and ideas in these materials.',
                'Examples in these materials are not to be taken as a promise or guarantee of earnings. Earning potential is entirely dependent on the person using our product, ideas, techniques and the effort put forth. We do not purport this as a "get rich scheme", and nor should you view it as such.',
                'Any and all forward looking statements here or on any of our sales material are intended to express our opinion of earnings potential. Many factors will be important in determining your actual results and no guarantees are made that you will achieve results similar to ours or anybody else’s, in fact no guarantees are made that you will achieve any results from our ideas and techniques.',
                'Results vary, and as with any money-making opportunity, you could make more or less. Success in ANY money-making opportunity is a result of hard work, time and a variety of other factors. No express or implied guarantees of income are made by TheSoftware.',
                'Returns and refunds policy: as stated, if you purchase TheSoftware, and you do not enjoy the financial freedom that you expected, do not make as much from our methods as you expected, or indeed for any reason, you may claim a refund for the product within 60 days of purchase. On a sidenote we do ask you to put the techniques into use before requesting a refund, for both our benefit: however, our refund policy is unconditional and this is a suggestion, not a requirement. We are aware that some buyers will not achieve their personal goals despite our best efforts to the contrary, and we stand by our refund policy as such. Please forward your receipt number (given to you when you ordered) to us and we will action your refund request as quickly as possible, typically within 24 hours.',
                'Revisions to This Policy: Our company reserves the right to revise, amend, or modify this policy, our Terms Of Service agreement, and our other policies and agreements at any time and in any manner, by updating this posting.',
            ]
        },
    ]

}

export const spam = {

    title: 'The Software Anti Spam Policy',
    toptext: [
        'This statement applies to TheSoftware websites and services that display or link to this notice (“Services”). TheSoftware prohibits the use of the Services in any manner associated with the transmission, distribution or delivery of any unsolicited bulk or unsolicited commercial e-mail (“Spam”). You may not use any Services to send Spam. You also may not deliver Spam or cause Spam to be delivered to any of TheSoftware Services or customers.',
        'In addition, e-mail sent, or caused to be sent, to or through the Services may not:\r\nUse or contain invalid or forged headers;\r\nUse or contain invalid or non-existent domain names;\r\nEmploy any technique to otherwise misrepresent, hide or obscure any information in identifying the point of origin or the transmission path;\r\nUse other means of deceptive addressing;\r\nUse a third party’s internet domain name, or be relayed from or through a third party’s equipment, without permission of the third party;\r\nContain false or misleading information in the subject line or otherwise contain false or misleading content;\r\nFail to comply with additional technical standards described below; or\r\nOtherwise violate the applicable Terms of Use for the Services.',
        'TheSoftware does not authorize the harvesting, mining or collection of e-mail addresses or other information from or through the Services. TheSoftware does not permit or authorize others to use the Services to collect, compile or obtain any information about TheSoftware’s customers or subscribers, including but not limited to subscriber e-mail addresses, which are TheSoftware’s confidential and proprietary information. Use of the Services is also subject to the applicable Privacy Statement and Terms of Use.',
        'TheSoftware does not permit or authorize any attempt to use the Services in a manner that could damage, disable, overburden or impair any aspect of any of the Services, or that could interfere with any other party’s use and enjoyment of any Service.',
        'If TheSoftware believes that unauthorized or improper use is being made of any Service, it may, without notice, take such action as it, in its sole discretion, deems appropriate, including blocking messages from a particular internet domain, mail server or IP address. TheSoftware may immediately terminate any account on any Service which it determines, in its sole discretion, is transmitting or is otherwise connected with any e-mail that violates this policy.',
        'Nothing in this policy is intended to grant any right to transmit or send e-mail to, or through, the Services. Failure to enforce this policy in every instance does not amount to a waiver of TheSoftware’s rights.',
        'Unauthorized use of the Services in connection with the transmission of unsolicited e-mail, including the transmission of e-mail in violation of this policy, may result in civil, criminal, or administrative penalties against the sender and those assisting the sender.',
    ],
    sections: []

}